tasks:
- name: make-initramfs
  pkgs_required:
  - zinnia-servers
  - mlibc
  args: [ '@SOURCE_ROOT@/tasks/make-initramfs.sh', '@SYSROOT_DIR@/boot/initramfs' ]
  workdir: '@BUILD_ROOT@'
  containerless: true
